# Generated by Django 3.1.2 on 2020-11-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NutInf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('nutval', models.ManyToManyField(to='NutInf.Nutinf')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='NutProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('nut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutInf.nutinf')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutInf.products')),
            ],
        ),
    ]
